### ISSUE TITLE
Managed cluster namespaces should be label to say `cluster backup operator managed cluster` and `accepted or not`

### ISSUE THREAD

**Issue by sdminonne** [open-cluster-management/cluster-backup-operator#45]
In order to have restore operator working properly we need to add a lable or an annotations (better a label) saying something like this:

`backup.cluster.open-cluster-manegement.io/accepted=true` or `backup.cluster.open-cluster-manegement.io/accepted=false`.
In this way we'll accomplish two goals
1. Understand which managed cluster namespace comes from a backup
2.  Understand which managed cluster namespace was accepted previously (already talked about this in a chat)

To be honest I don't care too much about the way accomplish this, but we need to solve both and this is the first idea I got (open for discussion)

**Comment by birsanv** [comment]
@sdminonne in order to track the tasks under the jira epic we need to create tasks under https://github.com/open-cluster-management/backlog/issues
Can you please move this task there

**Comment by sdminonne** [comment]
Closing since now it's tracked in https://github.com/open-cluster-management/backlog/issues/16122
